import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const svg = () => readFileSync(join(ROOT, 'docs/assets/boundary.svg'), 'utf8');

/**
 * The architecture picture, checked as claims rather than admired as a drawing.
 *
 * `demo-image.test.js` holds the other image on the front page to its
 * arithmetic. This one holds this image to its **facts**, and they are the
 * facts a reader is most likely to act on: which packages exist, what the core
 * depends on, and where this product may reach a network.
 *
 * The failure it exists to prevent is the one every architecture diagram in
 * every repository eventually has. The code moves, the picture does not, and
 * because a picture cannot be grepped nobody notices for a year — so the most
 * confident-looking artefact on the front page becomes the least true. Here it
 * is generated by `scripts/draw-architecture.mjs` from the same sources these
 * assertions read, and a workspace added without redrawing fails the build.
 */

/** Publishable workspaces, derived the same way `security.test.js` derives them. */
const publishable = () =>
  JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
    .workspaces.flatMap((pattern) => {
      const parent = pattern.replace(/\/\*$/, '');
      return readdirSync(join(ROOT, parent), { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => `${parent}/${entry.name}`);
    })
    .filter((path) => JSON.parse(readFileSync(join(ROOT, path, 'package.json'), 'utf8')).private !== true)
    .map((path) => JSON.parse(readFileSync(join(ROOT, path, 'package.json'), 'utf8')).name)
    .sort();

describe('the architecture picture says what is true', () => {
  it('is there, and is an SVG with something in it', () => {
    // Without this every assertion below could pass against an empty file.
    const text = svg();
    assert.match(text, /^<svg /m, 'docs/assets/boundary.svg is not an SVG');
    assert.ok(text.length > 2000, `the picture is ${text.length} bytes — has it been emptied?`);
  });

  it('names every package this repository publishes', () => {
    /**
     * The move people forget, and the reason this file exists: a package ships,
     * the picture stays as it was, and the front page shows an architecture
     * that has not been true since spring. Re-run
     * `npm run draw:architecture` and it is right again.
     */
    const text = svg();
    const missing = publishable().filter((name) => !text.includes(name));
    assert.deepEqual(
      missing,
      [],
      `these packages exist and the picture does not show them: ${missing.join(', ')}`,
    );
  });

  it('claims a dependency-free core only while the core has no dependencies', () => {
    const core = JSON.parse(readFileSync(join(ROOT, 'packages/core/package.json'), 'utf8'));
    const deps = Object.keys(core.dependencies ?? {});
    const claims = svg().includes('zero dependencies');
    assert.equal(
      claims && deps.length > 0,
      false,
      `the picture says "zero dependencies" and the core has: ${deps.join(', ')}`,
    );
    assert.ok(claims, 'the picture stopped making the claim the whole product rests on');
  });

  it('names exactly the modules that are allowed to reach a network', () => {
    /**
     * The sharpest of these, because it is the claim a security reviewer reads
     * first. `security.test.js` holds an allowlist of the modules that may
     * mention `fetch`, and the picture names them in prose. A third module
     * added to that list makes the picture quietly wrong about the one property
     * somebody chose this tool for.
     *
     * Read out of the test rather than typed here, so the two cannot drift.
     */
    const guard = readFileSync(join(ROOT, 'packages/core/test/security.test.js'), 'utf8');
    const declared = guard.match(/const allowed = new Set\(\[([^\]]*)\]\);[\s\S]{0,200}?srcDir/);
    assert.ok(declared, 'security.test.js no longer declares the network allowlist the same way');

    const allowed = [...declared[1].matchAll(/'([^']+)'/g)].map((match) => match[1]).sort();
    assert.ok(allowed.length > 0, 'the allowlist parsed to nothing');

    const text = svg();
    const unnamed = allowed.filter((module) => !text.includes(module));
    assert.deepEqual(
      unnamed,
      [],
      `these modules may reach a network and the picture does not say so: ${unnamed.join(', ')}`,
    );
  });

  it('points at a guard that exists for the promise it makes', () => {
    /**
     * The picture says `receipt-redaction.test.js` plants five things and fails
     * if any appears. A promise citing a file is worth exactly as much as the
     * file, so the citation is checked.
     */
    const text = svg();
    const cited = text.match(/([a-z-]+\.test\.js)/g) ?? [];
    assert.ok(cited.length > 0, 'the picture cites no guard for its central promise');

    const tests = new Set(readdirSync(join(ROOT, 'packages/core/test')));
    const absent = [...new Set(cited)].filter((name) => !tests.has(name));
    assert.deepEqual(absent, [], `the picture cites tests that do not exist: ${absent.join(', ')}`);
  });

  it('is regenerated rather than hand-edited', () => {
    // A picture somebody touched by hand is a picture that stops matching its
    // generator, and the generator is what the checks above are really about.
    const script = readFileSync(join(ROOT, 'scripts/draw-architecture.mjs'), 'utf8');
    assert.match(script, /boundary\.svg/, 'the generator no longer writes the file this checks');
  });
});
